<?php
/**
 * Gutenverse About Story content.
 */
return array(
	'title'      => __( 'Gutenverse About Story', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-93cU7N","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"50","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"0"}}}} -->
<div class="section-wrapper" data-id="93cU7N"><section class="wp-block-gutenverse-section guten-element guten-section guten-93cU7N layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-KVvpjN","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"35"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KVvpjN"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KVvpjN"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-4XuAwH","type":5,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h5-style-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400","style":"Italic"},"border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"positioningType":{"Desktop":"inline"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-4XuAwH animated guten-element-hide desktop-fadeInLeft">My Story</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-UGytz2","color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"34"},"Tablet":{"unit":"px","point":"34"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400","style":"Italic"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"},"hideDesktop":false,"hideTablet":false,"hideMobile":false} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-UGytz2 animated guten-element-hide desktop-fadeInLeft">Hi, My Name Is Kavana</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-RulDJv","textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"500"}} -->
<div class="guten-element gutenverse-text-editor guten-RulDJv animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-y3oT7Y","textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"35"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<div class="guten-element gutenverse-text-editor guten-y3oT7Y animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/image {"elementId":"guten-4asDiW","imgSrc":{"media":{"imageId":2012,"sizes":{"thumbnail":{"height":140,"width":150,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/signature-black@2x-8-150x140.webp","orientation":"landscape"},"medium":{"height":83,"width":300,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/signature-black@2x-8-300x83.webp","orientation":"landscape"},"full":{"url":"' . esc_url( KAVANA_URI ) . 'assets/img/signature-black@2x-8.webp","height":140,"width":508,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"170","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"align":{"Desktop":"left"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"30"}},"Tablet":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-4asDiW animated guten-element-hide desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( KAVANA_URI ) . 'assets/img/signature-black@2x-8.webp" height="140" width="508"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-IhMrOk","background":{"type":"default","image":{"Desktop":{"id":1347,"image":"' . esc_url( KAVANA_URI ) . 'assets/img/StockSnap_GW76AWE5JB.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"35"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-IhMrOk animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="IhMrOk"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-17C9ac","space":{"Desktop":{"point":"350","unit":"px"},"Mobile":{"point":"200","unit":"px"},"Tablet":{"point":"400","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-17C9ac"></div>
<!-- /wp:gutenverse/spacer --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
