<?php
/**
 * Gutenverse Home About Me content.
 */
return array(
	'title'      => __( 'Gutenverse Home About Me', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1170"},"gap":"no","elementId":"guten-In38DJ","background":{"type":"default","color":{"type":"variable","id":"primary"}},"margin":{"Mobile":{}},"padding":{"Mobile":{}}} -->
<div class="section-wrapper" data-id="In38DJ"><section class="wp-block-gutenverse-section guten-element guten-section guten-In38DJ layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-kSG6Vg","background":{"type":"default","image":{"Desktop":{"id":1347,"image":"' . esc_url( KAVANA_URI ) . 'assets/img/StockSnap_GW76AWE5JB.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-kSG6Vg animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="kSG6Vg"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-Gttxoi","space":{"Desktop":{"point":"608","unit":"px"},"Mobile":{"point":"200","unit":"px"},"Tablet":{"point":"400","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-Gttxoi"></div>
<!-- /wp:gutenverse/spacer --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-Z2qrIq","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"%","dimension":{"left":"","right":""}},"Tablet":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"80","left":"80"}},"Tablet":{"unit":"px","dimension":{"right":"20","top":"50","bottom":"35","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"30","bottom":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Z2qrIq"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Z2qrIq"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-rBTK8p","positioningType":{"Desktop":"custom","Tablet":"default"},"positioningWidth":{"Desktop":{"point":"510","unit":"px"}}} -->
<div class="section-wrapper" data-id="rBTK8p"><section class="wp-block-gutenverse-section guten-element guten-section guten-rBTK8p layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-IAchhz"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-IAchhz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="IAchhz"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-wu2ydh","type":5,"color":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"h5-style-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400","style":"Italic"},"border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"fifth"}}},"margin":{"Desktop":{"unit":"%","dimension":{"bottom":"0","left":"0","right":"0","top":"0"}},"Tablet":{"unit":"%","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"right":"70"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"},"positioningType":{"Desktop":"inline","Tablet":"inline"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-wu2ydh animated guten-element-hide desktop-fadeInRight">About Me</h5>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170","Tablet":""},"isChild":true,"gap":"no","elementId":"guten-by8B1c","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"510","unit":"px"}}} -->
<div class="section-wrapper" data-id="by8B1c"><section class="wp-block-gutenverse-section guten-element guten-section guten-by8B1c layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-bRrMFZ","horizontalAlign":{"Desktop":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"0","right":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"bottom":"0","right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bRrMFZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bRrMFZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-17tZr8","color":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"h2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"34"},"Tablet":{"unit":"px","point":"34"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400","style":"Italic"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"25","top":"20","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15"}},"Tablet":{"unit":"px","dimension":{"right":"0","bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-17tZr8 animated guten-element-hide desktop-fadeInRight">Hi, My Name Is Kavana </h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-99Hahq","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
<div class="guten-element gutenverse-text-editor guten-99Hahq animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-DN5boe","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
<div class="guten-element gutenverse-text-editor guten-DN5boe animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/image {"elementId":"guten-5N5oVi","imgSrc":{"media":{"imageId":1406,"sizes":{"thumbnail":{"height":142,"width":150,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/signature@2x-8-150x142.webp","orientation":"landscape"},"medium":{"height":129,"width":300,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/signature@2x-8-300x129.webp","orientation":"landscape"},"full":{"url":"' . esc_url( KAVANA_URI ) . 'assets/img/signature@2x-8.png","height":142,"width":330,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"170","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"align":{"Desktop":"left"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"700"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Tablet":{},"Mobile":{}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-5N5oVi animated guten-element-hide desktop-fadeInRight"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( KAVANA_URI ) . 'assets/img/signature@2x-8.png" height="142" width="330"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
