<?php
/**
 * Gutenverse Contact Main Bar content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Main Bar', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-nncJ6F","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"52","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"0"}}}} -->
<div class="section-wrapper" data-id="nncJ6F"><section class="wp-block-gutenverse-section guten-element guten-section guten-nncJ6F layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":66.66,"Tablet":100,"Mobile":null},"elementId":"guten-Rgha2b","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"right":"0","bottom":"52"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Rgha2b"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Rgha2b"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-LNSVpf","type":5,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h5-style-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400","style":"Italic"},"border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"},"positioningType":{"Desktop":"inline"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-LNSVpf animated guten-element-hide desktop-fadeInUp">Leave Me A Message</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-SuSPzu","gap":{"Desktop":{"point":"0","unit":"px"}},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"15","top":"15","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20","top":"20"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
<div class="guten-element gutenverse-text-editor guten-SuSPzu animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-E8zFNR","formId":{"label":"Leave A Message","value":448},"successPadding":{"Desktop":{}},"successBorder":{"radius":{"Desktop":{}}},"errorPadding":{"Desktop":{}},"errorBorder":{"radius":{"Desktop":{}}},"margin":{"Desktop":{},"Mobile":{},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
<form style="display:none" class="guten-element guten-form-builder guten-E8zFNR animated guten-element-hide desktop-fadeInUp" data-form-id="448"><!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-tFzkld","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
<div class="section-wrapper" data-id="tFzkld"><section class="wp-block-gutenverse-section guten-element guten-section guten-tFzkld layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null,"Tablet":null},"elementId":"guten-aKbV9D","margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-aKbV9D"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="aKbV9D"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-X2sYfv","inputLabel":"First Name","inputPlaceholder":"","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"primary"}},"labelTypography":{"type":"variable","id":"label-typography","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"400","transform":"Capitalize"},"labelPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"5"}},"Tablet":{},"Mobile":{}},"helperPadding":{"Desktop":{}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"10","bottom":"15","left":"10"}},"Tablet":{},"Mobile":{}},"inputMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"primary"}},"inputTypography":{"type":"variable","id":"input-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"color":{"type":"variable","id":"secondary"},"type":"solid","width":"1"}},"inputColorHover":{"Desktop":{"type":"variable","id":"secondary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-X2sYfv hide-helper"><div class="label-wrapper"><label class="input-label">First Name</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-KuNYbi","margin":{"Desktop":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KuNYbi"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KuNYbi"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-e1ucsL","inputLabel":"Last Name","inputPlaceholder":"","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"primary"}},"labelTypography":{"type":"variable","id":"label-typography","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"400","transform":"Capitalize"},"labelPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Tablet":{},"Mobile":{}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"10","bottom":"15","left":"10"}},"Tablet":{},"Mobile":{}},"inputMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"primary"}},"inputTypography":{"type":"variable","id":"input-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorHover":{"Desktop":{"type":"variable","id":"secondary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-e1ucsL hide-helper"><div class="label-wrapper"><label class="input-label">Last Name</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-qQCXgI","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
<div class="section-wrapper" data-id="qQCXgI"><section class="wp-block-gutenverse-section guten-element guten-section guten-qQCXgI layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-NP7eiM","margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-NP7eiM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="NP7eiM"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-email {"elementId":"guten-YnLO8q","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"primary"}},"labelTypography":{"type":"variable","id":"label-typography","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"400","transform":"Capitalize"},"labelPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":{},"Mobile":{}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputLabel":"Email Address","inputPlaceholder":"","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"10","bottom":"15","left":"10"}},"Tablet":{},"Mobile":{}},"inputMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"primary"}},"inputTypography":{"type":"variable","id":"input-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorHover":{"Desktop":{"type":"variable","id":"secondary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-YnLO8q hide-helper"><div class="label-wrapper"><label class="input-label">Email Address</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-rmd3Vh","margin":{"Desktop":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rmd3Vh"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rmd3Vh"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-telp {"elementId":"guten-UfhbpY","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"primary"}},"labelTypography":{"type":"variable","id":"label-typography","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"400","transform":"Capitalize"},"labelPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":{},"Mobile":{}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputLabel":"Phone Number","inputPlaceholder":"","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"10","bottom":"15","left":"10"}},"Tablet":{},"Mobile":{}},"inputMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"primary"}},"inputTypography":{"type":"variable","id":"input-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorHover":{"Desktop":{"type":"variable","id":"secondary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}}} -->
<div class="guten-element guten-form-input-telp guten-form-input guten-input-position-top guten-UfhbpY hide-helper"><div class="label-wrapper"><label class="input-label">Phone Number</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;telp&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="" name="input-telp" class="gutenverse-input gutenverse-input-tel" type="tel" pattern="[0-9]{3}-[0-9]{2}-[0-9]{3}"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-telp --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-wKsKFj","inputLabel":"Subject","inputPlaceholder":"","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"primary"}},"labelTypography":{"type":"variable","id":"label-typography","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"400","transform":"Capitalize"},"labelPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":{},"Mobile":{}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"10","bottom":"15","left":"10"}},"Tablet":{},"Mobile":{}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"primary"}},"inputTypography":{"type":"variable","id":"input-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorHover":{"Desktop":{"type":"variable","id":"secondary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-wKsKFj hide-helper"><div class="label-wrapper"><label class="input-label">Subject</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-bLmWX5","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"primary"}},"labelTypography":{"type":"variable","id":"label-typography","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"400","transform":"Capitalize"},"labelPadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":{},"Mobile":{}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputHeight":{"Desktop":"200"},"inputLabel":"Details","inputPlaceholder":"","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{},"Mobile":{}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"primary"}},"inputTypography":{"type":"variable","id":"input-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorHover":{"Desktop":{"type":"variable","id":"secondary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-bLmWX5 hide-helper"><div class="label-wrapper"><label class="input-label">Details</label></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-XUkyqh","content":"Send Message","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"seventh"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"button-font-2","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.125"},"weight":"400","transform":"Uppercase"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20"}},"Tablet":{},"Mobile":{}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-XUkyqh"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send Message</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100,"Mobile":null},"elementId":"guten-M3T2GI","margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-M3T2GI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="M3T2GI"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-84iw5a","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"}} -->
<div class="section-wrapper" data-id="84iw5a"><section class="wp-block-gutenverse-section guten-element guten-section guten-84iw5a animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-L2lUbd","background":{"type":"default","color":{"type":"variable","id":"primary"}},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"left":"0","bottom":"30"}},"Tablet":{"unit":"px","dimension":{"left":"0","bottom":"28"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-L2lUbd"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="L2lUbd"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-B3sH4r","imgSrc":{"media":{"imageId":1604,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/photo@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/photo@2x-8-300x300.webp","orientation":"landscape"},"full":{"url":"' . esc_url( KAVANA_URI ) . 'assets/img/photo@2x-8.webp","height":758,"width":758,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"80","unit":"px"}},"height":{"Desktop":{"point":"80","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":{}},"all":{"type":"solid","width":"3","color":{"type":"variable","id":"fifth"}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-B3sH4r"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( KAVANA_URI ) . 'assets/img/photo@2x-8.webp" height="758" width="758"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/heading {"elementId":"guten-lWAJLN","type":4,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"h4","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"25"},"Tablet":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-lWAJLN"><em>Kavana</em></h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-gV9XEk","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
<div class="guten-element gutenverse-text-editor guten-gV9XEk"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Quisque consectetur convallis ex, quis tincidunt ligula placerat et.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/image {"elementId":"guten-iTmJxh","imgSrc":{"media":{"imageId":1406,"sizes":{"thumbnail":{"height":142,"width":150,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/signature@2x-8-150x142.webp","orientation":"landscape"},"medium":{"height":129,"width":300,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/signature@2x-8-300x129.webp","orientation":"landscape"},"full":{"url":"' . esc_url( KAVANA_URI ) . 'assets/img/signature@2x-8.png","height":142,"width":330,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"100","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":{},"Tablet":{}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-iTmJxh"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( KAVANA_URI ) . 'assets/img/signature@2x-8.png" height="142" width="330"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-2KTjqg","type":5,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h5-style-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400","style":"Italic"},"border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","left":"5","right":"0"}},"Tablet":{"unit":"%","dimension":{"left":"0","right":"0","bottom":"0"}},"Mobile":{"unit":"%","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","bottom":"10"}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"},"positioningType":{"Desktop":"inline"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-2KTjqg animated guten-element-hide desktop-fadeInRight">Contact Information</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-b28B1v","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","top":"15"}},"Tablet":{"unit":"px","dimension":{"bottom":"35"}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"}} -->
<div class="section-wrapper" data-id="b28B1v"><section class="wp-block-gutenverse-section guten-element guten-section guten-b28B1v animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-4UXRfL","margin":{"Desktop":{"unit":"px","dimension":{"left":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"0","top":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-4UXRfL"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="4UXRfL"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-XEa1Vn","title":"Address","titleTag":"h6","description":"Jl. Sunset Road No.88, Kuta, Badung, Bali 80361, Indonesia","icon":"gtn gtn-map-pin-line","iconSize":{"Desktop":"20"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":""}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"5","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"title-blog-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":"1.5"},"Mobile":{"unit":"em","point":"1.5"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fourth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
<div class="guten-element guten-XEa1Vn guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-map-pin-line"></i></div></div><div class="icon-box icon-box-body"><h6 class="title">Address</h6><p class="icon-box-description">Jl. Sunset Road No.88, Kuta, Badung, Bali 80361, Indonesia</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-XM3Jrm","title":"Phone","titleTag":"h6","description":"Phone Number :  +62 (361) 234 567800\u003cbr\u003eFax : +62 (361) 555 5678 \u003cbr\u003eHotline : 1280 - 0822","icon":"gtn gtn-phone-call-line","iconSize":{"Desktop":"20"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"0","bottom":"10","left":"0"}}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"5","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"title-blog-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":"1.5"},"Mobile":{"unit":"em","point":"1.5"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fourth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
<div class="guten-element guten-XM3Jrm guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-phone-call-line"></i></div></div><div class="icon-box icon-box-body"><h6 class="title">Phone</h6><p class="icon-box-description">Phone Number :  +62 (361) 234 567800<br>Fax : +62 (361) 555 5678 <br>Hotline : 1280 - 0822</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-Rl8wLQ","title":"E-mail","titleTag":"h6","description":"kavana512@gmail.com\u003cbr\u003einfokavana@gmail.com","icon":"gtn gtn-email-light","iconSize":{"Desktop":"20"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"5","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"title-blog-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":"1.5"},"Mobile":{"unit":"em","point":"1.5"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fourth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Mobile":{}}} -->
<div class="guten-element guten-Rl8wLQ guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-email-light"></i></div></div><div class="icon-box icon-box-body"><h6 class="title">E-mail</h6><p class="icon-box-description">kavana512@gmail.com<br>infokavana@gmail.com</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
