<?php
/**
 * Gutenverse Contact Side Bar content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Side Bar', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-wU9Irf","verticalAlign":"flex-start","background":{"type":"default","color":{"type":"variable","id":"primary"},"image":{"Desktop":{}},"position":{"Desktop":"default"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"default"},"blendMode":{"Desktop":"normal"}},"backgroundOverlay":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"66","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}}} -->
<div class="section-wrapper" data-id="wU9Irf"><section class="wp-block-gutenverse-section guten-element guten-section guten-wU9Irf layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-FXO6fP","margin":{"Mobile":{},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Desktop":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Desktop":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-FXO6fP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="FXO6fP"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-5b5kLY","type":3,"color":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"h3","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"},"Tablet":{"unit":"px","point":"28"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-5b5kLY animated guten-element-hide desktop-fadeInLeft">Subscribe To My Newsletter</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-8soj2u","textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10","right":"25"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Mobile":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<div class="guten-element gutenverse-text-editor guten-8soj2u animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-jEKchI","verticalAlign":{"Desktop":"default"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-jEKchI animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jEKchI"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-4qTfBV","formId":{"label":"Email","value":449},"successPadding":{"Desktop":{}},"successBorder":{"radius":{"Desktop":{}}},"errorPadding":{"Desktop":{}},"errorBorder":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"5"}}}} -->
<form style="display:none" class="guten-element guten-form-builder guten-4qTfBV" data-form-id="449"><!-- wp:gutenverse/form-input-email {"elementId":"guten-21l6Uu","showLabel":false,"showHelper":false,"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"390"},"Tablet":{"unit":"%","point":"50"},"Mobile":{"unit":"%","point":"100"}},"positioningAlign":{"Desktop":"center"},"positioningLocation":"default","margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","bottom":"15"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":{},"Mobile":{}},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"20"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"sixth"}},"inputTypography":{"type":"variable","id":"input-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderFocus":{"radius":{"Desktop":{}}},"inputBgColorNormal":{"Desktop":{"r":255,"g":255,"b":255,"a":1}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-21l6Uu hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-LTG9Df","content":"Subscribe","buttonWidth":{"Tablet":"100","Mobile":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"buttonBorderHover":{"radius":{"Desktop":{}}},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"170"},"Mobile":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":"46"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{},"Tablet":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{},"Tablet":{}},"color":{"type":"variable","id":"fifth"},"typography":{"font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"type":"variable","id":"fifth"},"alignButton":{"Desktop":"flex-end","Mobile":"center","Tablet":"flex-end"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-LTG9Df"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Subscribe</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
