<?php
/**
 * Gutenverse About Biografi content.
 */
return array(
	'title'      => __( 'Gutenverse About Biografi', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-jXzTRt","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}}} -->
<div class="section-wrapper" data-id="jXzTRt"><section class="wp-block-gutenverse-section guten-element guten-section guten-jXzTRt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-65RpHZ","order":{"Tablet":2},"background":{"type":"default","image":{"Desktop":{"id":1996,"image":"' . esc_url( KAVANA_URI ) . 'assets/img/StockSnap_0Y0YL5907B.webp"}},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"35"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-65RpHZ animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="65RpHZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-N2FTdM","space":{"Desktop":{"point":"400","unit":"px"},"Tablet":{"point":"500","unit":"px"},"Mobile":{"point":"300","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-N2FTdM"></div>
<!-- /wp:gutenverse/spacer --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-t2nhf2","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"35"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"35","bottom":"50"}},"Mobile":{"unit":"px","dimension":{"bottom":"30","top":"30"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-t2nhf2"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="t2nhf2"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-983WIG","type":5,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h5-style-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400","style":"Italic"},"border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"top":"","right":"0","bottom":"0","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Mobile":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"},"positioningType":{"Desktop":"inline"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-983WIG animated guten-element-hide desktop-fadeInUp">Biography</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-GF1U1h","title":"2022 : Discover the world\'s wonders","titleTag":"h4","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","icon":"gtn gtn-arrow-right-line","iconSize":{"Desktop":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"12"}}},"iconMargin":{"Desktop":{}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h4","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"25"},"Tablet":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fourth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","left":"-5"}},"Tablet":{"unit":"px","dimension":{"top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"5"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<div class="guten-element guten-GF1U1h animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-arrow-right-line"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">2022 : Discover the world\'s wonders</h4><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-0UBiG4","title":"2018 : Publish My First Story","titleTag":"h4","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","icon":"gtn gtn-arrow-right-line","iconSize":{"Desktop":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"12"}}},"iconMargin":{"Desktop":{}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h4","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"25"},"Tablet":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fourth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","left":"-5"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"500"}} -->
<div class="guten-element guten-0UBiG4 animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-arrow-right-line"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">2018 : Publish My First Story</h4><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-oV9VbU","title":"2016 : The Journey Was Began","titleTag":"h4","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","icon":"gtn gtn-arrow-right-line","iconSize":{"Desktop":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"12"}}},"iconMargin":{"Desktop":{}},"iconColor":{"type":"variable","id":"third"},"iconHoverColor":{"type":"variable","id":"third"},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{},"Mobile":{}},"titleColor":{"type":"variable","id":"primary"},"titleHoverColor":{"type":"variable","id":"primary"},"titleTypography":{"type":"variable","id":"h4","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"25"},"Tablet":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"descColor":{"type":"variable","id":"fourth"},"descHoverColor":{"type":"variable","id":"fourth"},"descTypography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","left":"-5"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"700"}} -->
<div class="guten-element guten-oV9VbU animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-arrow-right-line"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">2016 : The Journey Was Began</h4><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
