<?php
/**
 * Gutenverse About Explore content.
 */
return array(
	'title'      => __( 'Gutenverse About Explore', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-OqkCte","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"50","bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"30"}}}} -->
<div class="section-wrapper" data-id="OqkCte"><section class="wp-block-gutenverse-section guten-element guten-section guten-OqkCte layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-X75cW4","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-X75cW4"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="X75cW4"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-hvMqIA","type":5,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h5-style-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400","style":"Italic"},"border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"secondary"}}},"margin":{"Desktop":{"unit":"%","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"%","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"%","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"none","Tablet":"fadeInUp"},"duration":"normal","delay":""},"positioningType":{"Desktop":"inline"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-hvMqIA animated guten-element-hide tablet-fadeInUp">Explore The Topics</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-Cu5rhY","margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
<div class="section-wrapper" data-id="Cu5rhY"><section class="wp-block-gutenverse-section guten-element guten-section guten-Cu5rhY layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":20,"Mobile":50},"elementId":"guten-VPDSC4","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VPDSC4 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VPDSC4"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-duSrYH","imgSrc":{"media":{"imageId":1311,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/travel@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/travel@2x-8-300x300.webp","orientation":"landscape"},"large":{"height":1024,"width":1024,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/travel@2x-8.webp","orientation":"landscape"},"full":{"url":"' . esc_url( KAVANA_URI ) . 'assets/img/travel@2x-8.webp","height":1388,"width":1388,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"90","unit":"px"}},"url":"#","imgBorder":{"radius":{"Desktop":{},"Tablet":{}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-duSrYH"><a class="guten-image-wrapper" href="#"><img class="gutenverse-image-box-filled" src="' . esc_url( KAVANA_URI ) . 'assets/img/travel@2x-8.webp" height="1388" width="1388"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/button {"elementId":"guten-cBIogp","content":"Travel","url":"#","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"13"}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-font-2","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.0125"},"weight":"400","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"third"}} -->
<div class="guten-element guten-button-wrapper guten-cBIogp"><a class="guten-button guten-button-sm" href="#"><span>Travel</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":20,"Mobile":50},"elementId":"guten-sTd3tC","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-sTd3tC animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="sTd3tC"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-U6oa9F","imgSrc":{"media":{"imageId":1313,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/lifestyle@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/lifestyle@2x-8-300x300.webp","orientation":"landscape"},"large":{"height":1024,"width":1024,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/lifestyle@2x-8.webp","orientation":"landscape"},"full":{"url":"' . esc_url( KAVANA_URI ) . 'assets/img/lifestyle@2x-8.webp","height":1388,"width":1388,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"90","unit":"px"}},"url":"#","imgBorder":{"radius":{"Desktop":{},"Tablet":{}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-U6oa9F"><a class="guten-image-wrapper" href="#"><img class="gutenverse-image-box-filled" src="' . esc_url( KAVANA_URI ) . 'assets/img/lifestyle@2x-8.webp" height="1388" width="1388"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/button {"elementId":"guten-7nn5Y8","content":"Lifestyle","url":"#","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"13"}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-font-2","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.0125"},"weight":"400","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"third"}} -->
<div class="guten-element guten-button-wrapper guten-7nn5Y8"><a class="guten-button guten-button-sm" href="#"><span>Lifestyle</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":20,"Mobile":50},"elementId":"guten-63gli6","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-63gli6 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="63gli6"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-WZ2SWw","imgSrc":{"media":{"imageId":1314,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/food@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/food@2x-8-300x300.webp","orientation":"landscape"},"large":{"height":1024,"width":1024,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/food@2x-8.webp","orientation":"landscape"},"full":{"url":"' . esc_url( KAVANA_URI ) . 'assets/img/food@2x-8.webp","height":1388,"width":1388,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"90","unit":"px"}},"url":"#","imgBorder":{"radius":{"Desktop":{},"Tablet":{}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-WZ2SWw"><a class="guten-image-wrapper" href="#"><img class="gutenverse-image-box-filled" src="' . esc_url( KAVANA_URI ) . 'assets/img/food@2x-8.webp" height="1388" width="1388"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/button {"elementId":"guten-wp1Kyy","content":"Food \u0026 Drink","url":"#","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"13"}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-font-2","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.0125"},"weight":"400","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"third"}} -->
<div class="guten-element guten-button-wrapper guten-wp1Kyy"><a class="guten-button guten-button-sm" href="#"><span>Food & Drink</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":20,"Mobile":50},"elementId":"guten-tTOpnF","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"30"}},"Desktop":{}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-tTOpnF animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="tTOpnF"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-mEGaEI","imgSrc":{"media":{"imageId":1315,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/Fashion@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/Fashion@2x-8-300x300.webp","orientation":"landscape"},"large":{"height":1024,"width":1024,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/Fashion@2x-8.webp","orientation":"landscape"},"full":{"url":"' . esc_url( KAVANA_URI ) . 'assets/img/Fashion@2x-8.webp","height":1388,"width":1388,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"90","unit":"px"}},"url":"#","imgBorder":{"radius":{"Desktop":{},"Tablet":{}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-mEGaEI"><a class="guten-image-wrapper" href="#"><img class="gutenverse-image-box-filled" src="' . esc_url( KAVANA_URI ) . 'assets/img/Fashion@2x-8.webp" height="1388" width="1388"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/button {"elementId":"guten-p9bVVW","content":"Fashion","url":"#","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"13"}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-font-2","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.0125"},"weight":"400","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"third"}} -->
<div class="guten-element guten-button-wrapper guten-p9bVVW"><a class="guten-button guten-button-sm" href="#"><span>Fashion</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":20,"Mobile":null},"elementId":"guten-8dqwPX","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-8dqwPX animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8dqwPX"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-ALIXtt","imgSrc":{"media":{"imageId":1316,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/beauty@2x-8-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/beauty@2x-8-300x300.webp","orientation":"landscape"},"large":{"height":1024,"width":1024,"url":"' . esc_url( KAVANA_URI ) . 'assets/img/beauty@2x-8.webp","orientation":"landscape"},"full":{"url":"' . esc_url( KAVANA_URI ) . 'assets/img/beauty@2x-8.webp","height":1388,"width":1388,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"90","unit":"px"}},"url":"#","imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-ALIXtt"><a class="guten-image-wrapper" href="#"><img class="gutenverse-image-box-filled" src="' . esc_url( KAVANA_URI ) . 'assets/img/beauty@2x-8.webp" height="1388" width="1388"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/button {"elementId":"guten-ueQ46B","content":"Beauty","url":"#","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"13"}}},"padding":{"Desktop":{}},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button-font-2","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.0125"},"weight":"400","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"third"}} -->
<div class="guten-element guten-button-wrapper guten-ueQ46B"><a class="guten-button guten-button-sm" href="#"><span>Beauty</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
