<?php
/**
 * Gutenverse Single Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Single Hero', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-7rLL4l","background":{"type":"default","image":{"Desktop":{"id":1731,"image":"' . esc_url( KAVANA_URI ) . 'assets/img/StockSnap_DH08J1VTZX.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"blendMode":{"Desktop":"overlay"}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"primary"}},"opacity":"0.6","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"100"}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"340","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"250","bottom":"50","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"150","right":"20","left":"20","bottom":"50"}}}} -->
<div class="section-wrapper" data-id="7rLL4l"><section class="wp-block-gutenverse-section guten-element guten-section guten-7rLL4l layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-bNaS5I","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bNaS5I"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bNaS5I"><div class="guten-column-wrapper"><!-- wp:gutenverse/post-terms {"elementId":"guten-HWLCQU","taxonomy":"post_tag","alignment":{"Desktop":"center"},"typography":{"type":"variable","id":"h6-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"},"Tablet":{"unit":"px","point":"15"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"Uppercase"},"color":{"type":"variable","id":"third"},"colorHover":{"type":"variable","id":"third"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
<div class="guten-element guten-post-terms guten-HWLCQU animated guten-element-hide desktop-fadeInUp"></div>
<!-- /wp:gutenverse/post-terms -->

<!-- wp:gutenverse/post-title {"elementId":"guten-mm2dGL","alignment":{"Desktop":"center"},"typography":{"type":"variable","id":"h1-style-2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"64"},"Tablet":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"36"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400","style":"Italic"},"color":{"type":"variable","id":"fifth"},"colorHover":"","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<div class="guten-element guten-post-title guten-mm2dGL animated guten-element-hide desktop-fadeInUp"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/icon {"elementId":"guten-xATv6n","icon":"gtn gtn-user-light","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"fifth"},"iconColorHoverOne":{"r":0,"g":0,"b":0,"a":0},"iconColorHoverTwo":{"type":"variable","id":"fifth"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-xATv6n guten-icon animated guten-element-hide desktop-fadeInUp"><span class="guten-icon-wrapper rounded stacked"><i class="gtn gtn-user-light"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-author {"elementId":"guten-h6NfOa","typography":{"type":"variable","id":"input-style-12","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"color":{"type":"variable","id":"fifth"},"colorHover":{"type":"variable","id":"fifth"},"authorBorder":{"radius":{"Desktop":{},"Mobile":{}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-author guten-h6NfOa animated guten-element-hide desktop-fadeInUp"></div>
<!-- /wp:gutenverse/post-author -->

<!-- wp:gutenverse/icon {"elementId":"guten-Inwdra","icon":"gtn gtn-calendar-line","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"16","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"fifth"},"iconColorHoverOne":{"r":0,"g":0,"b":0,"a":0},"iconColorHoverTwo":{"type":"variable","id":"fifth"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"30","top":"3"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-Inwdra guten-icon animated guten-element-hide desktop-fadeInUp"><span class="guten-icon-wrapper rounded stacked"><i class="gtn gtn-calendar-line"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-date {"elementId":"guten-w9B3dq","typography":{"type":"variable","id":"input-style-12","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"color":{"type":"variable","id":"fifth"},"colorHover":{"type":"variable","id":"fifth"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-date guten-w9B3dq animated guten-element-hide desktop-fadeInUp"></div>
<!-- /wp:gutenverse/post-date --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
