<?php
/**
 * Gutenverse Home Popup content.
 */
return array(
	'title'      => __( 'Gutenverse Home Popup', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-mdrX2E"} -->
<div class="section-wrapper" data-id="mdrX2E"><section class="wp-block-gutenverse-section guten-element guten-section guten-mdrX2E layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-vXBM6F"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vXBM6F"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vXBM6F"><div class="guten-column-wrapper"><!-- wp:gutenverse/popup-builder {"elementId":"guten-rCXqAp","width":{"Desktop":{"point":"700","unit":"px"},"Tablet":{"unit":"%","point":"85"},"Mobile":{"point":"85","unit":"%"}},"maxHeight":{"Desktop":{"point":"","unit":"vh"}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"40","bottom":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"30","left":"20"}},"Tablet":{}},"containerBorder":{"radius":{"Desktop":{},"Mobile":{},"Tablet":{}}},"closeButtonColor":{"Desktop":{"r":29,"g":27,"b":21,"a":1},"Mobile":{"r":0,"g":0,"b":0,"a":0}},"closeButtonBgColor":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"closeButtonSize":{"Desktop":"20"},"closePositioningRight":{"Desktop":{"point":"15","unit":"px"}},"closePositioningTop":{"Desktop":{"point":"15","unit":"px"}},"closePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"closeBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"closeButtonColorHover":{"Desktop":{"r":173,"g":117,"b":49,"a":1}},"closeBorderHover":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"openWaitTime":"5"} -->
<div class="guten-element guten-popup-builder guten-rCXqAp" data-trigger="load" data-wait="5" data-close-overlay="true"><div class="guten-popup guten-popup-center guten-popup-side-space"><div class="guten-popup-overlay"></div><div class="guten-popup-wrapper guten-popup-wrapper-center"><div class="guten-popup-content"><div class="guten-popup-close"><i class="gtn gtn-x-line"></i></div><div class="guten-popup-container"><!-- wp:gutenverse/popup-container {"elementId":"guten-jetXUh","position":"above"} -->
<div class="guten-element guten-popup-content-inner above"><div class="guten-popup-content-wrapper"><!-- wp:gutenverse/section {"gap":"no","elementId":"guten-Dcq28L"} -->
<div class="section-wrapper" data-id="Dcq28L"><section class="wp-block-gutenverse-section guten-element guten-section guten-Dcq28L layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":45,"Mobile":100},"elementId":"guten-LAnmdZ","background":{"type":"default","image":{"Desktop":{"id":4187,"image":"' . esc_url( KAVANA_URI ) . 'assets/img/StockSnap_MQTBLC6B5V.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-LAnmdZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LAnmdZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-x3Aenc","space":{"Desktop":{"point":"350","unit":"px"},"Mobile":{"point":"160","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-x3Aenc"></div>
<!-- /wp:gutenverse/spacer --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":55,"Mobile":100,"Tablet":null},"elementId":"guten-i019gr","verticalAlign":{"Desktop":"center","Mobile":"center","Tablet":"center"},"horizontalAlign":{"Desktop":"center","Mobile":"center","Tablet":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Mobile":{"unit":"px","dimension":{"left":"0"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-i019gr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="i019gr"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-QZa0Nw","textAlign":{"Mobile":"center","Desktop":"center","Tablet":"center"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"34"},"Tablet":{"unit":"px","point":"34"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400","style":"Italic"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Mobile":{}},"positioningType":{"Desktop":"inline"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-QZa0Nw">Don\'t Miss Out!</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-J5ZwvJ","alignment":{"Mobile":"center","Desktop":"center"},"textColor":{"type":"variable","id":"fourth"},"typography":{"type":"variable","id":"text-editor-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{}},"padding":{"Mobile":{},"Desktop":{},"Tablet":{}}} -->
<div class="guten-element gutenverse-text-editor guten-J5ZwvJ"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Subscribe to my newsletter to get the latest topic.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-50KIiI","successPadding":{"Desktop":{}},"successBorder":{"radius":{"Desktop":{}}},"errorPadding":{"Desktop":{}},"errorBorder":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{}}} -->
<form style="display:none" class="guten-element guten-form-builder guten-50KIiI"><!-- wp:gutenverse/form-input-email {"elementId":"guten-7bxwv5","showLabel":false,"showHelper":false,"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":"100"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"15"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputPlaceholder":"Enter Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"20","left":"10"}},"Mobile":{}},"inputMargin":{"Desktop":{},"Mobile":{}},"placeholderColor":{"Desktop":{"type":"variable","id":"secondary"}},"inputTypography":{"type":"variable","id":"input-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-7bxwv5 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Enter Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-EMxWmA","content":"Subscribe","buttonWidth":{"Desktop":"100","Mobile":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"seventh"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"all":{"type":"none","width":"","color":""}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none","width":"","color":""}},"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":"100"}},"border":{"radius":{"Desktop":{}}},"borderHover":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"color":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"button-font-2","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"em","point":"1"},"Mobile":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.125"},"weight":"400","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"fifth"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20"}},"Mobile":{}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-EMxWmA"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Subscribe</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/popup-container --></div></div></div></div></div>
<!-- /wp:gutenverse/popup-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
