<?php
/**
 * Gutenverse Archive Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Archive Hero', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-y1fzii","background":{"type":"default","image":{"Desktop":{"id":2121,"image":"' . esc_url( KAVANA_URI ) . 'assets/img/StockSnap_0BJHJZTG7D.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"primary"}},"opacity":"0.7","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"340","bottom":"70"}},"Tablet":{"unit":"px","dimension":{"bottom":"50","top":"250","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"50","top":"150"}}}} -->
<div class="section-wrapper" data-id="y1fzii"><section class="wp-block-gutenverse-section guten-element guten-section guten-y1fzii layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-BFg001","verticalAlign":{"Desktop":"default","Mobile":"default"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-BFg001"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="BFg001"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-N1Lbtj","type":6,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"h6-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"},"Tablet":{"unit":"px","point":"15"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"Uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-N1Lbtj animated guten-element-hide desktop-fadeInUp">Category</h6>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-Ku5aW5","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<div class="section-wrapper" data-id="Ku5aW5"><section class="wp-block-gutenverse-section guten-element guten-section guten-Ku5aW5 animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-bdI2dL","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bdI2dL"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bdI2dL"><div class="guten-column-wrapper"><!-- wp:query-title {"type":"archive","showPrefix":false,"style":{"typography":{"fontSize":"64px"},"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"textColor":"fifth","className":"is-style-customposttitle","fontFamily":"primary"} /--></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
