<?php
/**
 * Gutenverse Home Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'kavana' ),
	'categories' => array( 'kavana-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-26lp0Y","background":{"type":"default","image":{"Desktop":{"id":1301,"image":"' . esc_url( KAVANA_URI ) . 'assets/img/StockSnap_ZJ3GHBCGZ4.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"340","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"50","top":"250"}},"Mobile":{"unit":"px","dimension":{"bottom":"50","top":"150"}}}} -->
<div class="section-wrapper" data-id="26lp0Y"><section class="wp-block-gutenverse-section guten-element guten-section guten-26lp0Y layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-1qUYVc","margin":{"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}},"Mobile":{},"Desktop":{"unit":"%","dimension":{"right":"15","left":"15","top":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}},"Desktop":{}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1qUYVc"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1qUYVc"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-yciuoc","type":6,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"h6-style-1","font":{"label":"Josefin Sans","value":"Josefin Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"},"Tablet":{"unit":"px","point":"15"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.2"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"Uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"10","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Tablet":"fadeInUp","Desktop":"fadeInUp"},"duration":"normal"}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-yciuoc animated guten-element-hide desktop-fadeInUp tablet-fadeInUp">Welcome To My Blog</h6>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-zQVXqm","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"h1-style-1","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"64"},"Tablet":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"36"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"unit":"em","point":"1.3"},"Mobile":{"unit":"em","point":"1.3"}},"weight":"400","style":"Italic"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-zQVXqm animated guten-element-hide desktop-fadeInUp">My Name Is <em>Kavana</em> &amp; This Is My Personal <em>Journey</em></h1>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
